version: '3'

tasks:
  build:
    desc: Build the 'project' CLI
    cmds:
      - mkdir -p bin
      - go build -o bin/project cmd/project/main.go
      - chmod +x bin/project
    sources:
      - "**/*.go"
    generates:
      - "bin/project"

  run:
    desc: Run the 'project' CLI from source
    cmds:
      - go run cmd/project/main.go {{.CLI_ARGS}}
    silent: true

  clean:
    desc: Remove built artifacts
    cmds:
      - rm -rf bin

  install:
    desc: Install the 'project' CLI to /usr/local/bin
    deps:
      - build
    cmds:
      - sudo mkdir -p /usr/local/bin
      - sudo cp bin/project /usr/local/bin/

  uninstall:
    desc: Uninstall the 'project' CLI from /usr/local/bin
    cmds:
      - sudo rm /usr/local/bin/project
